# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RockPaperScissorsFinalProj.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RockPaperScissors(object):
    def setupUi(self, RockPaperScissors):
        RockPaperScissors.setObjectName("RockPaperScissors")
        RockPaperScissors.resize(310, 273)
        RockPaperScissors.setMinimumSize(QtCore.QSize(310, 273))
        RockPaperScissors.setMaximumSize(QtCore.QSize(310, 273))
        self.centralwidget = QtWidgets.QWidget(RockPaperScissors)
        self.centralwidget.setObjectName("centralwidget")
        self.Submit = QtWidgets.QPushButton(self.centralwidget)
        self.Submit.setGeometry(QtCore.QRect(100, 190, 101, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Submit.sizePolicy().hasHeightForWidth())
        self.Submit.setSizePolicy(sizePolicy)
        self.Submit.setObjectName("Submit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 10, 151, 21))
        self.label.setObjectName("label")
        self.browser_Game = QtWidgets.QTextBrowser(self.centralwidget)
        self.browser_Game.setGeometry(QtCore.QRect(40, 50, 221, 101))
        self.browser_Game.setObjectName("browser_Game")
        self.radioButton_Rock = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_Rock.setGeometry(QtCore.QRect(10, 160, 82, 17))
        self.radioButton_Rock.setObjectName("radioButton_Rock")
        self.radioButton_Paper = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_Paper.setGeometry(QtCore.QRect(110, 160, 82, 17))
        self.radioButton_Paper.setObjectName("radioButton_Paper")
        self.radioButton_Scissors = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_Scissors.setGeometry(QtCore.QRect(210, 160, 82, 17))
        self.radioButton_Scissors.setObjectName("radioButton_Scissors")
        RockPaperScissors.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RockPaperScissors)
        self.statusbar.setObjectName("statusbar")
        RockPaperScissors.setStatusBar(self.statusbar)

        self.retranslateUi(RockPaperScissors)
        QtCore.QMetaObject.connectSlotsByName(RockPaperScissors)

    def retranslateUi(self, RockPaperScissors):
        _translate = QtCore.QCoreApplication.translate
        RockPaperScissors.setWindowTitle(_translate("RockPaperScissors", "Rock Paper Scissors"))
        self.Submit.setText(_translate("RockPaperScissors", "Submit"))
        self.label.setText(_translate("RockPaperScissors", "--Rock -- Paper -- Scissors--"))
        self.radioButton_Rock.setText(_translate("RockPaperScissors", "Rock"))
        self.radioButton_Paper.setText(_translate("RockPaperScissors", "Paper"))
        self.radioButton_Scissors.setText(_translate("RockPaperScissors", "Scissors"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RockPaperScissors = QtWidgets.QMainWindow()
    ui = Ui_RockPaperScissors()
    ui.setupUi(RockPaperScissors)
    RockPaperScissors.show()
    sys.exit(app.exec_())
